### ISSUE TITLE
PyQt6/PySide6 support

### ISSUE THREAD

**Issue by botsman11** [polfeliu/pyreaqtive#12]
Hello.
This project is very interesting. 
Are you planning to add PySide6 support?

**Comment by polfeliu** [comment]
Hello, I've just rewritten the imports with qtpy. It's not as elegant or practical as I thought, once you start using qtpy, pyqt5 typing stubs stop working. For the moment the best solution is to import pyqt if type checking, essentially you can make programs that work with pyreaqtive but if they are not using pyqt5 you must removed them from the type checking scope.

https://github.com/polfeliu/pyreaqtive/tree/issue-12-PyQt6/PySide6_support

I've done a quick test with pyqt6. Let me know if you find any issue!

**Comment by botsman11** [comment]
Thank you! I will test it this week.

**Comment by botsman11** [comment]
Sorry for so late answer. Unfortunately I don't have time to work on my own project. I will close this issue. May be I will return to it in future.

**Comment by polfeliu** [comment]
Don't Worry. I haven't had the time to fully validate it, I will leave the branch open in case there's interest on it.

**Comment by polfeliu** [comment]
Hello, I've just released version 1.4.0 that has all the new recent improvements and compatbility with PyQt6, and PySide2/6!
