### ISSUE TITLE
Convert normal class instance to reactive

### ISSUE THREAD

**Issue by polfeliu** [polfeliu/pyreaqtive#2]
Function that takes an object and converts all compatible attributes from static to reactive.

The replaced models must have the same base-type inherited

Also overrides `__setattr__ `for other code that may access the attribute. Redirects changes of attributes to .set()

**Comment by polfeliu** [comment]
Error:
type 'bool' is not an acceptable base type

Should not be a runtime problem. All models have return types according to their respecitive type:
__bool__ for example

**Comment by ierror** [comment]
Thanks for your work! Is it possible convert e.g. `LineEdit` into `RQLineEdit` and make it reactive? I could't find anything in the docs.

**Comment by polfeliu** [comment]
Thanks! Right now, not directly, you would have a to connect the signals and slots of the model and the LineEdit manually. 
In what situation would you need this?
Reactivization (rq_getattr and rq_getlist) right now is only meant for models.

**Comment by ierror** [comment]
ah sorry, mixed it up. I have an app created with the Designer (loading .ui files) where I want to use your lib.

**Comment by polfeliu** [comment]
I've never been a fan of qtdesigner files, I almost always write the views from scratch. You can always leave the space to latter inject the widget.

Don't know if this might help: https://doc.qt.io/qt-6/designer-using-custom-widgets.html

**Comment by ierror** [comment]
Thank you! It does not work because I need to add the model to pyreaqtive widgets. I will try to implement my own "hacky" solution connecting the signals manually :)
